module.exports = [
  {
    id: 1,
    email: "demo@gicportal.com",
    password: "123456",
    role: "admin",
    userGroup: 1,
    firstName: "Quoc",
    lastName: "Cuong Pao",
    gender: "Male",
    avatarUrl: "https://atlaskit.atlassian.com//75257be97d303fd5def46f93e3484d07.png",
    description:
      "in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non",
    department: 10,
    officePhoneNumber: "(788) 2528838",
    mobile: "329-742-6877",
    maritalStatus: "married",
    personalID: "3556549612782381"
  },
  {
    id: 2,
    email: "hdacca1@gizmodo.com",
    password: "ceFfBKXrMv",
    role: "moderator",
    userGroup: 4,
    gender: "Male",
    firstName: "Haley",
    lastName: "Dacca",
    avatarUrl: "https://randomuser.me/api/portraits/lego/8.jpg",
    description: "eu est congue elementum in hac habitasse platea dictumst morbi",
    department: 6,
    officePhoneNumber: "(985) 2337281",
    mobile: "893-599-2995",
    maritalStatus: "divorced",
    personalID: "3553205265278515"
  },
  {
    id: 3,
    email: "mglassard2@so-net.ne.jp",
    password: "BHkYonUI",
    role: "moderator",
    userGroup: 1,
    gender: "Male",
    firstName: "Maurice",
    lastName: "Glassard",
    avatarUrl: "https://randomuser.me/api/portraits/lego/9.jpg",
    description:
      "orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus",
    department: 8,
    officePhoneNumber: "(693) 5052203",
    mobile: "617-684-7539",
    maritalStatus: "separated",
    personalID: "30377500002577"
  },
  {
    id: 4,
    email: "nrowberry3@deliciousdays.com",
    password: "4wS2Ea",
    role: "admin",
    userGroup: 3,
    gender: "Male",
    firstName: "Norman",
    lastName: "Rowberry",
    avatarUrl: "https://randomuser.me/api/portraits/lego/1.jpg",
    description: "etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam",
    department: 5,
    officePhoneNumber: "(675) 6574120",
    mobile: "197-733-2982",
    maritalStatus: "divorced",
    personalID: "201752459969252"
  },
  {
    id: 5,
    email: "jackery4@dyndns.org",
    password: "1NPFVpdiuNei",
    role: "moderator",
    userGroup: 3,
    gender: "Female",
    firstName: "Jerrylee",
    lastName: "Ackery",
    avatarUrl: "https://randomuser.me/api/portraits/lego/8.jpg",
    description: "quis tortor id nulla ultrices aliquet maecenas leo odio condimentum",
    department: 3,
    officePhoneNumber: "(483) 3370951",
    mobile: "528-515-1253",
    maritalStatus: "engaged",
    personalID: "676180172459395998"
  },
  {
    id: 6,
    email: "lgoter5@webs.com",
    password: "502VoLbNM4p",
    role: "admin",
    userGroup: 1,
    gender: "Male",
    firstName: "Les",
    lastName: "Goter",
    avatarUrl: "https://randomuser.me/api/portraits/lego/8.jpg",
    description:
      "fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in",
    department: 7,
    officePhoneNumber: "(187) 3673932",
    mobile: "930-360-6273",
    maritalStatus: "widower",
    personalID: "5602237144402723"
  },
  {
    id: 7,
    email: "ekimblin6@craigslist.org",
    password: "QmqWxI8JEN",
    role: "standard",
    userGroup: 1,
    gender: "Male",
    firstName: "Eadmund",
    lastName: "Kimblin",
    avatarUrl: "https://randomuser.me/api/portraits/lego/9.jpg",
    description:
      "ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis",
    department: 5,
    officePhoneNumber: "(856) 2763298",
    mobile: "659-239-8000",
    maritalStatus: "engaged",
    personalID: "6762521592266399"
  },
  {
    id: 8,
    email: "irochewell7@ifeng.com",
    password: "fcMHW3BccD",
    role: "moderator",
    userGroup: 3,
    gender: "Female",
    firstName: "Isabelle",
    lastName: "Rochewell",
    avatarUrl: "https://randomuser.me/api/portraits/lego/6.jpg",
    description:
      "dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet",
    department: 4,
    officePhoneNumber: "(932) 4364330",
    mobile: "578-498-7371",
    maritalStatus: "widow",
    personalID: "4041374584833257"
  },
  {
    id: 9,
    email: "cpeevor8@psu.edu",
    password: "etwOqmo",
    role: "moderator",
    userGroup: 4,
    gender: "Female",
    firstName: "Collete",
    lastName: "Peevor",
    avatarUrl: "https://randomuser.me/api/portraits/lego/7.jpg",
    description:
      "eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante",
    department: 1,
    officePhoneNumber: "(661) 9823192",
    mobile: "699-772-8910",
    maritalStatus: "widower",
    personalID: "3565440790037328"
  },
  {
    id: 10,
    email: "sjaume9@mac.com",
    password: "G2ZRLfnK9qDz",
    role: "admin",
    userGroup: 2,
    gender: "Male",
    firstName: "Simone",
    lastName: "Jaume",
    avatarUrl: "https://randomuser.me/api/portraits/lego/4.jpg",
    description:
      "mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu",
    department: 9,
    officePhoneNumber: "(516) 7966528",
    mobile: "204-783-4381",
    maritalStatus: "widower",
    personalID: "3539917039785034"
  },
  {
    id: 11,
    email: "bstoddarda@bing.com",
    password: "sg5pr7SwN",
    role: "admin",
    userGroup: 4,
    gender: "Female",
    firstName: "Babbie",
    lastName: "Stoddard",
    avatarUrl: "https://randomuser.me/api/portraits/lego/7.jpg",
    description:
      "consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius",
    department: 4,
    officePhoneNumber: "(833) 2607037",
    mobile: "167-436-0070",
    maritalStatus: "single",
    personalID: "374288533857230"
  },
  {
    id: 12,
    email: "fgreenrdeb@bing.com",
    password: "h8GsOaKzW",
    role: "moderator",
    userGroup: 3,
    gender: "Female",
    firstName: "Fancy",
    lastName: "Greenrde",
    avatarUrl: "https://randomuser.me/api/portraits/lego/4.jpg",
    description:
      "venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut",
    department: 8,
    officePhoneNumber: "(467) 7895103",
    mobile: "278-221-3684",
    maritalStatus: "widow",
    personalID: "63045938915891960"
  },
  {
    id: 13,
    email: "brollc@earthlink.net",
    password: "P2TNNZ1l",
    role: "standard",
    userGroup: 3,
    gender: "Female",
    firstName: "Bree",
    lastName: "Roll",
    avatarUrl: "https://randomuser.me/api/portraits/lego/7.jpg",
    description:
      "sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam",
    department: 8,
    officePhoneNumber: "(517) 3429885",
    mobile: "722-989-8273",
    maritalStatus: "married",
    personalID: "201830132383016"
  },
  {
    id: 14,
    email: "rtippelld@istockphoto.com",
    password: "OjCGIt2jHx",
    role: "admin",
    userGroup: 3,
    gender: null,
    firstName: null,
    lastName: null,
    avatarUrl: null,
    description: null,
    department: null,
    officePhoneNumber: null,
    mobile: null,
    maritalStatus: null,
    personalID: null
  },
  {
    id: 15,
    email: "ssayburne@icq.com",
    password: "Iu9YEf0",
    role: "moderator",
    userGroup: 1,
    gender: "Female",
    firstName: "Serene",
    lastName: "Sayburn",
    avatarUrl: "https://randomuser.me/api/portraits/lego/8.jpg",
    description: "proin eu mi nulla ac enim in tempor turpis nec euismod",
    department: 1,
    officePhoneNumber: "(932) 8297356",
    mobile: "275-148-6317",
    maritalStatus: "separated",
    personalID: "3572004260429430"
  },
  {
    id: 16,
    email: "kmanstonf@skype.com",
    password: "LvxEuWCV5",
    role: "admin",
    userGroup: 1,
    gender: "Female",
    firstName: "Kathrine",
    lastName: "Manston",
    avatarUrl: "https://randomuser.me/api/portraits/lego/1.jpg",
    description:
      "vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit",
    department: 3,
    officePhoneNumber: "(775) 2374264",
    mobile: "158-592-6717",
    maritalStatus: "separated",
    personalID: "3574575840844626"
  },
  {
    id: 17,
    email: "ocrockg@360.cn",
    password: "dH7GcTdCr",
    role: "standard",
    userGroup: 4,
    gender: "Male",
    firstName: "Ode",
    lastName: "Crock",
    avatarUrl: "https://randomuser.me/api/portraits/lego/3.jpg",
    description:
      "ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id",
    department: 2,
    officePhoneNumber: "(647) 7878989",
    mobile: "140-627-3662",
    maritalStatus: "widow",
    personalID: "589368937504274961"
  },
  {
    id: 18,
    email: "wvolkerh@wsj.com",
    password: "t5vTae1CPP",
    role: "standard",
    userGroup: 2,
    gender: "Male",
    firstName: "Wayne",
    lastName: "Volker",
    avatarUrl: "https://randomuser.me/api/portraits/lego/9.jpg",
    description: "cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit",
    department: 7,
    officePhoneNumber: "(618) 3969004",
    mobile: "720-796-6944",
    maritalStatus: "widower",
    personalID: "36018217789551"
  },
  {
    id: 19,
    email: "hreynardi@jimdo.com",
    password: "zPmgcG8D",
    role: "moderator",
    userGroup: 1,
    gender: "Male",
    firstName: "Herculie",
    lastName: "Reynard",
    avatarUrl: "https://randomuser.me/api/portraits/lego/9.jpg",
    description:
      "mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue",
    department: 6,
    officePhoneNumber: "(463) 4242232",
    mobile: "569-573-1019",
    maritalStatus: "divorced",
    personalID: "5007661579849721"
  },
  {
    id: 20,
    email: "mteodorij@msn.com",
    password: "kVctUS0qdRg8",
    role: "standard",
    userGroup: 1,
    gender: "Female",
    firstName: "Meridel",
    lastName: "Teodori",
    avatarUrl: "https://randomuser.me/api/portraits/lego/2.jpg",
    description:
      "lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa",
    department: 4,
    officePhoneNumber: "(358) 9773857",
    mobile: "179-667-0653",
    maritalStatus: "separated",
    personalID: "6387780300581193"
  }
];
