module.exports = [
  {
    id: 1,
    email: "demo@gicportal.com",
    password: "123456",
    role: "admin",
    userGroup: 1,
    departmentID: "Marketing",
    positionID: "CMO",
    firstName: "Quoc",
    lastName: "Cuong Pao",
    gender: "Male",
    avatarUrl: "https://atlaskit.atlassian.com//75257be97d303fd5def46f93e3484d07.png",
    description:
      "in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non",
    officePhoneNumber: "(788) 2528838",
    mobile: "329-742-6877",
    maritalStatus: "married",
    personalID: "3556549612782381"
  },
  {
    id: 2,
    email: "rthurber1@vk.com",
    password: "PQbO774N57",
    role: "admin",
    userGroup: 1,
    departmentID: 9,
    positionID: 1,
    gender: "Female",
    firstName: "Ruthanne",
    lastName: "Thurber",
    avatarUrl: "https://randomuser.me/api/portraits/lego/3.jpg",
    description:
      "erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit",
    officePhoneNumber: "(302) 3905273",
    mobile: "290-258-6298",
    maritalStatus: "widow",
    IDCardNumber: "6396775301201212"
  },
  {
    id: 3,
    email: "ghucknall2@nymag.com",
    password: "OFDnwM",
    role: "standard",
    userGroup: 3,
    departmentID: 10,
    positionID: 3,
    gender: "Male",
    firstName: "Geri",
    lastName: "Hucknall",
    avatarUrl: "https://randomuser.me/api/portraits/lego/3.jpg",
    description:
      "quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie",
    officePhoneNumber: "(943) 9542482",
    mobile: "435-386-3529",
    maritalStatus: "widow",
    IDCardNumber: "201584235320645"
  },
  {
    id: 4,
    email: "dburnhard3@acquirethisname.com",
    password: "pRM8Sd5bjc2",
    role: "admin",
    userGroup: 4,
    departmentID: 8,
    positionID: 2,
    gender: "Female",
    firstName: "Dredi",
    lastName: "Burnhard",
    avatarUrl: "https://randomuser.me/api/portraits/lego/3.jpg",
    description:
      "nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante",
    officePhoneNumber: "(249) 1179497",
    mobile: "913-710-5945",
    maritalStatus: "divorced",
    IDCardNumber: "3562457537989739"
  },
  {
    id: 5,
    email: "arapi4@mac.com",
    password: "I0vJWAV",
    role: "admin",
    userGroup: 4,
    departmentID: 2,
    positionID: 2,
    gender: "Female",
    firstName: "Annecorinne",
    lastName: "Rapi",
    avatarUrl: "https://randomuser.me/api/portraits/lego/1.jpg",
    description:
      "nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at",
    officePhoneNumber: "(893) 3509958",
    mobile: "439-783-7337",
    maritalStatus: "separated",
    IDCardNumber: "3581243569239343"
  },
  {
    id: 6,
    email: "nkeford5@craigslist.org",
    password: "8p5VX0TWjMEw",
    role: "standard",
    userGroup: 4,
    departmentID: 2,
    positionID: 2,
    gender: "Female",
    firstName: "Ninnetta",
    lastName: "Keford",
    avatarUrl: "https://randomuser.me/api/portraits/lego/3.jpg",
    description:
      "vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate",
    officePhoneNumber: "(286) 5467329",
    mobile: "825-154-9241",
    maritalStatus: "separated",
    IDCardNumber: "201426737704910"
  },
  {
    id: 7,
    email: "melliston6@nsw.gov.au",
    password: "MwWsVJfOZf",
    role: "moderator",
    userGroup: 2,
    departmentID: 3,
    positionID: 2,
    gender: "Male",
    firstName: "Morlee",
    lastName: "Elliston",
    avatarUrl: "https://randomuser.me/api/portraits/lego/1.jpg",
    description:
      "nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit",
    officePhoneNumber: "(631) 4359858",
    mobile: "782-585-8436",
    maritalStatus: "widower",
    IDCardNumber: "6394756296467275"
  },
  {
    id: 8,
    email: "charrowell7@facebook.com",
    password: "nyM7nl7zi4",
    role: "admin",
    userGroup: 1,
    departmentID: 4,
    positionID: 3,
    gender: "Female",
    firstName: "Celisse",
    lastName: "Harrowell",
    avatarUrl: "https://randomuser.me/api/portraits/lego/6.jpg",
    description: "mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula",
    officePhoneNumber: "(885) 4088432",
    mobile: "987-751-6053",
    maritalStatus: "engaged",
    IDCardNumber: "3578469755501361"
  },
  {
    id: 9,
    email: "elegendre8@tripadvisor.com",
    password: "Rqx85Or1FD6m",
    role: "admin",
    userGroup: 2,
    departmentID: 11,
    positionID: 3,
    gender: "Female",
    firstName: "Elenore",
    lastName: "Legendre",
    avatarUrl: "https://randomuser.me/api/portraits/lego/7.jpg",
    description:
      "nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi",
    officePhoneNumber: "(496) 8142033",
    mobile: "228-976-6518",
    maritalStatus: "engaged",
    IDCardNumber: "677145760974339418"
  },
  {
    id: 10,
    email: "rvolke9@noaa.gov",
    password: "TYxtvt",
    role: "admin",
    userGroup: 3,
    departmentID: 1,
    positionID: 1,
    gender: "Male",
    firstName: "Reinaldos",
    lastName: "Volke",
    avatarUrl: "https://randomuser.me/api/portraits/lego/4.jpg",
    description:
      "praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras",
    officePhoneNumber: "(217) 4791253",
    mobile: "103-964-4633",
    maritalStatus: "widow",
    IDCardNumber: "4844049797219036"
  },
  {
    id: 11,
    email: "ttomkinsa@mysql.com",
    password: "MrYOjUJUtQjM",
    role: "standard",
    userGroup: 4,
    departmentID: 8,
    positionID: 3,
    gender: "Male",
    firstName: "Tedd",
    lastName: "Tomkins",
    avatarUrl: "https://randomuser.me/api/portraits/lego/9.jpg",
    description:
      "sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac",
    officePhoneNumber: "(214) 6207512",
    mobile: "675-861-3045",
    maritalStatus: "separated",
    IDCardNumber: "30400023251131"
  },
  {
    id: 12,
    email: "mherculsonb@1688.com",
    password: "rzJ1pfT5",
    role: "standard",
    userGroup: 3,
    departmentID: 9,
    positionID: 1,
    gender: "Male",
    firstName: "Manuel",
    lastName: "Herculson",
    avatarUrl: "https://randomuser.me/api/portraits/lego/7.jpg",
    description: "aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue",
    officePhoneNumber: "(112) 7368369",
    mobile: "588-374-5481",
    maritalStatus: "widower",
    IDCardNumber: "3573073588136026"
  },
  {
    id: 13,
    email: "mharnellc@imdb.com",
    password: "hKEKRT",
    role: "admin",
    userGroup: 1,
    departmentID: 11,
    positionID: 2,
    gender: "Female",
    firstName: "Molly",
    lastName: "Harnell",
    avatarUrl: "https://randomuser.me/api/portraits/lego/6.jpg",
    description: "sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed",
    officePhoneNumber: "(391) 4640778",
    mobile: "517-668-0041",
    maritalStatus: "widower",
    IDCardNumber: "3562552490230004"
  },
  {
    id: 14,
    email: "mmenchentond@skype.com",
    password: "J7hwCe21hr",
    role: "standard",
    userGroup: 2,
    departmentID: 6,
    positionID: 3,
    gender: "Female",
    firstName: "Malvina",
    lastName: "Menchenton",
    avatarUrl: "https://randomuser.me/api/portraits/lego/2.jpg",
    description:
      "dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque",
    officePhoneNumber: "(882) 9170058",
    mobile: "215-665-8763",
    maritalStatus: "single",
    IDCardNumber: "372301248181093"
  },
  {
    id: 15,
    email: "ljonahe@prweb.com",
    password: "s1AHsX02WOI",
    role: "admin",
    userGroup: 4,
    departmentID: 11,
    positionID: 2,
    gender: "Female",
    firstName: "Lydia",
    lastName: "Jonah",
    avatarUrl: "https://randomuser.me/api/portraits/lego/2.jpg",
    description:
      "in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis",
    officePhoneNumber: "(429) 7295860",
    mobile: "987-933-5683",
    maritalStatus: "widower",
    IDCardNumber: "675913526657245899"
  },
  {
    id: 16,
    email: "atimewellf@answers.com",
    password: "G1T6eD",
    role: "standard",
    userGroup: 1,
    departmentID: 1,
    positionID: 3,
    gender: "Female",
    firstName: "Annabal",
    lastName: "Timewell",
    avatarUrl: "https://randomuser.me/api/portraits/lego/5.jpg",
    description:
      "consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque",
    officePhoneNumber: "(153) 7614054",
    mobile: "408-606-9554",
    maritalStatus: "widow",
    IDCardNumber: "3535384534239872"
  },
  {
    id: 17,
    email: "ogeroldinig@soup.io",
    password: "IWYbBm0a",
    role: "standard",
    userGroup: 3,
    departmentID: 1,
    positionID: 3,
    gender: "Male",
    firstName: "Olivero",
    lastName: "Geroldini",
    avatarUrl: "https://randomuser.me/api/portraits/lego/8.jpg",
    description: "amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo",
    officePhoneNumber: "(934) 3207904",
    mobile: "208-805-2230",
    maritalStatus: "divorced",
    IDCardNumber: "5602243372060613690"
  },
  {
    id: 18,
    email: "tsmallcombeh@moonfruit.com",
    password: "bWjLK9NKAq25",
    role: "standard",
    userGroup: 4,
    departmentID: 11,
    positionID: 3,
    gender: "Female",
    firstName: "Torey",
    lastName: "Smallcombe",
    avatarUrl: "https://randomuser.me/api/portraits/lego/5.jpg",
    description: "ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et",
    officePhoneNumber: "(656) 8205228",
    mobile: "393-637-4617",
    maritalStatus: "widower",
    IDCardNumber: "3566238198762417"
  },
  {
    id: 19,
    email: "hwharltoni@list-manage.com",
    password: "9eLCDR",
    role: "admin",
    userGroup: 1,
    departmentID: 4,
    positionID: 3,
    gender: "Male",
    firstName: "Hammad",
    lastName: "Wharlton",
    avatarUrl: "https://randomuser.me/api/portraits/lego/5.jpg",
    description:
      "pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla",
    officePhoneNumber: "(381) 2836848",
    mobile: "142-799-5571",
    maritalStatus: "single",
    IDCardNumber: "4913514094107065"
  },
  {
    id: 20,
    email: "ksideyj@odnoklassniki.ru",
    password: "rqXPzKwziOmj",
    role: "standard",
    userGroup: 4,
    departmentID: 8,
    positionID: 1,
    gender: "Male",
    firstName: "Kean",
    lastName: "Sidey",
    avatarUrl: "https://randomuser.me/api/portraits/lego/9.jpg",
    description: "velit eu est congue elementum in hac habitasse platea dictumst morbi",
    officePhoneNumber: "(632) 7422665",
    mobile: "254-460-7572",
    maritalStatus: "widow",
    IDCardNumber: "374283885301390"
  }
];
