module.exports = [
  {
    id: 1,
    email: "demo@gicportal.com",
    password: "123456",
    role: "admin",
    userGroup: 1,
    firstName: "Quoc",
    lastName: "Cuong Pao",
    gender: "Male",
    avatarUrl: "https://atlaskit.atlassian.com//75257be97d303fd5def46f93e3484d07.png",
    description:
      "in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non",
    department: 10,
    officePhoneNumber: "(788) 2528838",
    mobile: "329-742-6877",
    maritalStatus: "married",
    personalID: "3556549612782381"
  },
  {
    id: 2,
    firstName: null,
    lastName: null,
    email: "mmonteith1@army.mil",
    password: "GZ19wMO",
    role: "moderator",
    userGroup: 4,
    gender: null,
    avatarUrl: null,
    description: null,
    department: null,
    officePhoneNumber: null,
    mobile: null,
    maritalStatus: null,
    personalID: null
  },
  {
    id: 3,
    firstName: "Thaddus",
    lastName: "Hearfield",
    email: "thearfield2@example.com",
    password: "hPVF7HsSoPws",
    role: "standard",
    userGroup: 3,
    gender: "Male",
    avatarUrl: "https://randomuser.me/api/portraits/Male/92.jpg",
    description:
      "in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non",
    department: 10,
    officePhoneNumber: "(788) 2528838",
    mobile: "329-742-6877",
    maritalStatus: "married",
    personalID: "3556549612782381"
  },
  {
    id: 4,
    firstName: "Mavis",
    lastName: "Heaton",
    email: "mheaton3@utexas.edu",
    password: "jjirX6",
    role: "admin",
    userGroup: 2,
    gender: "Female",
    avatarUrl: "https://randomuser.me/api/portraits/Female/35.jpg",
    description: "sed tristique in tempus sit amet sem fusce consequat nulla",
    department: 5,
    officePhoneNumber: "(464) 5201438",
    mobile: "812-151-1315",
    maritalStatus: "divorced",
    personalID: "3537387756344625"
  },
  {
    id: 5,
    firstName: "Gilemette",
    lastName: "Gowen",
    email: "ggowen4@moonfruit.com",
    password: "SdF0sTQWo",
    role: "admin",
    userGroup: 3,
    gender: "Female",
    avatarUrl: "https://randomuser.me/api/portraits/Female/11.jpg",
    description:
      "eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer",
    department: 3,
    officePhoneNumber: "(585) 4587604",
    mobile: "609-278-8860",
    maritalStatus: "widow",
    personalID: "374288709606544"
  },
  {
    id: 6,
    firstName: "Percy",
    lastName: "Inggall",
    email: "pinggall5@umich.edu",
    password: "ouDtebr",
    role: "standard",
    userGroup: 4,
    gender: "Male",
    avatarUrl: "https://randomuser.me/api/portraits/Male/61.jpg",
    description:
      "hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum",
    department: 4,
    officePhoneNumber: "(145) 6913488",
    mobile: "979-233-3614",
    maritalStatus: "divorced",
    personalID: "372948865371785"
  },
  {
    id: 7,
    firstName: "Benton",
    lastName: "Vango",
    email: "bvango6@themeforest.net",
    password: "CAU8OuvdU",
    role: "moderator",
    userGroup: 4,
    gender: "Male",
    avatarUrl: "https://randomuser.me/api/portraits/Male/92.jpg",
    description:
      "habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante",
    department: 1,
    officePhoneNumber: "(139) 5237247",
    mobile: "168-491-7818",
    maritalStatus: "widower",
    personalID: "6372058593507192"
  },
  {
    id: 8,
    firstName: "Jenine",
    lastName: "Linskill",
    email: "jlinskill7@histats.com",
    password: "hEKWrlgpqNvu",
    role: "standard",
    userGroup: 2,
    gender: "Female",
    avatarUrl: "https://randomuser.me/api/portraits/Female/36.jpg",
    description:
      "nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat",
    department: 1,
    officePhoneNumber: "(363) 9007821",
    mobile: "981-608-3852",
    maritalStatus: "separated",
    personalID: "6304321568286934"
  },
  {
    id: 9,
    firstName: "Ulysses",
    lastName: "Kraft",
    email: "ukraft8@irs.gov",
    password: "2s6fAxJmQ",
    role: "admin",
    userGroup: 1,
    gender: "Male",
    avatarUrl: "https://randomuser.me/api/portraits/Male/53.jpg",
    description: "tempus sit amet sem fusce consequat nulla nisl nunc nisl",
    department: 5,
    officePhoneNumber: "(136) 8851521",
    mobile: "665-671-8921",
    maritalStatus: "widow",
    personalID: "676141347897763449"
  },
  {
    id: 10,
    firstName: "Regen",
    lastName: "McPaik",
    email: "rmcpaik9@china.com.cn",
    password: "KCezJU",
    role: "moderator",
    userGroup: 4,
    gender: "Male",
    avatarUrl: "https://randomuser.me/api/portraits/Male/56.jpg",
    description: "aenean sit amet justo morbi ut odio cras mi pede malesuada",
    department: 2,
    officePhoneNumber: "(253) 4645013",
    mobile: "853-958-4096",
    maritalStatus: "married",
    personalID: "6763923720024477"
  },
  {
    id: 11,
    firstName: "Robinet",
    lastName: "Edwick",
    email: "redwicka@jalbum.net",
    password: "18HsYEIq4hOv",
    role: "standard",
    userGroup: 1,
    gender: "Male",
    avatarUrl: "https://randomuser.me/api/portraits/Male/65.jpg",
    description: "felis fusce posuere felis sed lacus morbi sem mauris laoreet",
    department: 2,
    officePhoneNumber: "(650) 4516917",
    mobile: "715-337-9983",
    maritalStatus: "single",
    personalID: "3579351613837071"
  },
  {
    id: 12,
    firstName: null,
    lastName: null,
    email: "fcasob@1und1.de",
    password: "ytH1siD",
    role: "standard",
    userGroup: 2,
    gender: null,
    avatarUrl: null,
    description: null,
    department: null,
    officePhoneNumber: null,
    mobile: null,
    maritalStatus: null,
    personalID: null
  },
  {
    id: 13,
    firstName: "Jarrad",
    lastName: "Stiegar",
    email: "jstiegarc@mtv.com",
    password: "wKWpnZIz",
    role: "moderator",
    userGroup: 2,
    gender: "Male",
    avatarUrl: "https://randomuser.me/api/portraits/Male/70.jpg",
    description: "felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl",
    department: 5,
    officePhoneNumber: "(154) 3987944",
    mobile: "567-984-3759",
    maritalStatus: "widow",
    personalID: "3584556500812648"
  },
  {
    id: 14,
    firstName: "Krystle",
    lastName: "Boutton",
    email: "kbouttond@friendfeed.com",
    password: "AKb7KRv7FJ",
    role: "moderator",
    userGroup: 3,
    gender: "Female",
    avatarUrl: "https://randomuser.me/api/portraits/Female/45.jpg",
    description:
      "sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia",
    department: 5,
    officePhoneNumber: "(245) 6942102",
    mobile: "534-595-1292",
    maritalStatus: "engaged",
    personalID: "3563036016513977"
  },
  {
    id: 15,
    firstName: "Maye",
    lastName: "Di Carli",
    email: "mdicarlie@sohu.com",
    password: "frrttz8Q",
    role: "moderator",
    userGroup: 4,
    gender: "Female",
    avatarUrl: "https://randomuser.me/api/portraits/Female/8.jpg",
    description:
      "nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante",
    department: 8,
    officePhoneNumber: "(692) 2283414",
    mobile: "330-812-5307",
    maritalStatus: "divorced",
    personalID: "3558820272302135"
  },
  {
    id: 16,
    firstName: "Cyndie",
    lastName: "Tinghill",
    email: "ctinghillf@a8.net",
    password: "wyVWNn91yXQ",
    role: "admin",
    userGroup: 1,
    gender: "Female",
    avatarUrl: "https://randomuser.me/api/portraits/Female/24.jpg",
    description:
      "ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy",
    department: 3,
    officePhoneNumber: "(966) 2166597",
    mobile: "677-780-2341",
    maritalStatus: "engaged",
    personalID: "3573777089610368"
  },
  {
    id: 17,
    firstName: "Walton",
    lastName: "Manass",
    email: "wmanassg@princeton.edu",
    password: "A4WuoTzbkFQR",
    role: "moderator",
    userGroup: 3,
    gender: "Male",
    avatarUrl: "https://randomuser.me/api/portraits/Male/39.jpg",
    description:
      "vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor",
    department: 2,
    officePhoneNumber: "(889) 9198823",
    mobile: "247-306-2265",
    maritalStatus: "widow",
    personalID: "30594298430949"
  },
  {
    id: 18,
    firstName: "Aubry",
    lastName: "Clapp",
    email: "aclapph@smugmug.com",
    password: "Ql6Qq36NPLn",
    role: "moderator",
    userGroup: 4,
    gender: "Female",
    avatarUrl: "https://randomuser.me/api/portraits/Female/13.jpg",
    description:
      "pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit",
    department: 2,
    officePhoneNumber: "(757) 9279839",
    mobile: "332-195-6420",
    maritalStatus: "widower",
    personalID: "3534541908739461"
  },
  {
    id: 19,
    firstName: null,
    lastName: null,
    email: "ejorgenseni@nytimes.com",
    password: "m9c69pi",
    role: "moderator",
    userGroup: 4,
    gender: null,
    avatarUrl: null,
    description: null,
    department: null,
    officePhoneNumber: null,
    mobile: null,
    maritalStatus: null,
    personalID: null
  },
  {
    id: 20,
    firstName: "Cecil",
    lastName: "Branthwaite",
    email: "cbranthwaitej@trellian.com",
    password: "jdxQpZMoI",
    role: "moderator",
    userGroup: 3,
    gender: "Male",
    avatarUrl: "https://randomuser.me/api/portraits/Male/45.jpg",
    description:
      "tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel",
    department: 1,
    officePhoneNumber: "(539) 6836782",
    mobile: "812-708-2527",
    maritalStatus: "widow",
    personalID: "3546099627015131"
  }
];
